language: node_js
node_js:
  - 7
  - 6
  - 4

install:
  - npm config set spin=false
  - npm install

script:
  - npm test

after_script:
  - npm install -g coveralls
  - npm run coverage
  - cat ./coverage/lcov.info | coveralls

sudo: false
